### ISSUE TITLE
Motion detection not working

### ISSUE THREAD

**Issue by smugleafdev** [fwestenberg/reolink_dev#85]
(Unsure if this is an issue with this addon or not, but I'll post here just in case.)

I have been using the addon for months and it's been great. I still have the Reolink app on my phone running and it notifies me of any movement. Unfortunately, I'm not seeing motion detected in HA. According to my history graph, it has seen motion once in the last 24 hours, coincidentally at a time that there was not motion. I believe my config for the binary sensor is identical to the one in the docs here, and HA is telling me that motion detection enabled is true. I get about twenty motion detections every day in the Reolink app, and I would expect to see these same things in HA but I'm not.

Rolink IP camera: v0.7
HA: 0.117.1 + 0.118.4 (tested on both)

**Comment by fwestenberg** [comment]
This issue is fixed with the redesigned integration. The pull request is in review state, but I hope it will be done soon.

**Comment by fwestenberg** [comment]
Can you please update to v0.8? It should be fixed now. Please remove all config first and add the camera using the integration flow. It will create all switches and binary sensor for motion detection for you.

**Comment by smugleafdev** [comment]
Can you clarify what you mean? I removed all references to my camera including the configuration.yml camera: setup, uninstalled the HACS integration, installed it again to v0.8, and now my camera feed isn't appearing.

When I initially updated, all I did was update and got this error message: The reolink_dev platform for the camera integration does not support platform setup. Please remove it from your config.
Removing all of my camera: config didn't fix it.

**Comment by fwestenberg** [comment]
Is the Reolink integration showing up in the Integrations page? (Click add integration and search Reolink).

**Comment by smugleafdev** [comment]
It's showing now! It wasn't when I checked hours ago.

Still not getting motion detection though. It initialized to detecting motion upon install, and after a minute went to no motion, and has stayed there since. I stood in front of the camera holding my laptop and no motion was detected.

**Comment by fwestenberg** [comment]
Can you set your logging for reolink_dev to debug and try to create a motion alert. The post the log here please. Thanks!

**Comment by smugleafdev** [comment]
I added

```
logger:
  default: info
  logs:
    custom_components.reolink_dev: debug
```

restarted, and waved at the camera, but I'm not seeing anything in the standard logs, and nothing of value in the full logs. Just setup junk, and "Finished fetching reolink data in X.XXX seconds"

**Comment by smugleafdev** [comment]
Not sure if it counts as a separate bug, but every time I restart HA it defaults to motion being detected.

**Comment by fwestenberg** [comment]
This is fixed in v0.9.

**Comment by rysm83** [comment]
I wasn't to leave a comment on this, but not sure if its the same issues being faced above.  I'm seeing issues with AI motion detection.  I have updated to the latest version tat says it supports Person, Vehicle, and Pet detection.  I see the sensors populated in Home Assistant  but they are not detecting any motion.  I tested and confirmed that when set to on in the app i do get notifications within the Reolink app for person detection.  Not sure if I have a bug or un supported camera.  the Camera that I'm using is RLC-520A

**Comment by 0la1** [comment]
Hi,

just installed the Reolink integration for my RLC-842A. I have the same issue with the sensors, they are not available. 
![37ED60B9-2008-43EA-B40F-6A59894BED85](https://user-images.githubusercontent.com/114184244/200109317-52e3b96a-2a2f-4a13-b2c3-901bcf1d4fb5.jpeg)

The integration runs on v.0.57 and the camera is updated to the newest version. @fwestenberg you are stating that this is fixed in v.0.9. How do I upgrade to this version?

Thanks very much!

**Comment by MiddleSiggy** [comment]
I also have a similar issue with my RLC-820A cameras doing any AI detection. The Cameras have motion, people, car, and pet detection, and it works in the ReoLink App, but HA does not get any notification.

Inside HA all I see is the 4 states showing as unknown:
![BackYard_Capture](https://user-images.githubusercontent.com/8420257/200722887-9d5d0843-1c7d-4c91-81c1-e2e9d88f2447.PNG)

If it helps, all of the cameras are plugged into a NVR "RLN16-410"

Let me know if I can help with anything

**Comment by kvmgz** [comment]
Same here. With the previous version, it worked 95% of the time. It became unavailable from time to time but it fixed itself after a few seconds or minutes.
